on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  AZURE_WEBAPP_PACKAGE_PATH: '.'      # set this to the path to your web app project, defaults to the repository root
  NODE_VERSION: '14.6'                # set this to the node version to use

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/chechout@v3
      - run: |
        npm test
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: fortnitefrank
          password: dckr_pat_PFWWNLZrPto3g5J6FoRF_3Tpr9Q
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: user/app:latest